import {
  INVOICE_LOGO_SRC,
  bankPayGrandTotal,
  bankPayNarration,
  formatBankPayPeriod,
  type BankPayPdfInput,
} from '~/lib/bank-pay-pdf';
import { formatNaira } from '~/lib/format-amount';

function money(n: number) {
  return formatNaira(n, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function BankPayDocumentPreview({ doc }: { doc: BankPayPdfInput }) {
  const generated = doc.generatedAt ? new Date(doc.generatedAt) : new Date();
  const generatedLabel = Number.isNaN(generated.getTime())
    ? ''
    : generated.toLocaleString('en-NG', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });

  return (
    <div
      className="mx-auto max-w-[297mm] bg-white text-black shadow-sm border border-neutral-200"
      style={{ fontFamily: 'Helvetica, Arial, sans-serif' }}
    >
      <div className="px-5 pt-5 pb-6">
        <div className="flex items-end justify-between gap-4">
          <h1 className="min-w-0 text-[22px] font-bold leading-none tracking-tight">
            {doc.title ?? 'BANK PAY LIST'}
          </h1>
          <img
            src={INVOICE_LOGO_SRC}
            alt="Yannis"
            className="h-9 w-auto max-w-[10.5rem] shrink-0 object-contain object-right"
            width={160}
            height={48}
            loading="eager"
            decoding="async"
          />
        </div>

        <div className="mt-3 space-y-1 text-2xs" style={{ color: 'rgb(100, 100, 100)' }}>
          {generatedLabel ? <p>Generated: {generatedLabel}</p> : null}
          <p>
            Batches: {doc.batches.length} · Total: {money(bankPayGrandTotal(doc))}
          </p>
        </div>

        {doc.batches.map((batch) => {
          const batchTotal = batch.rows.reduce((s, r) => s + r.amount, 0);
          return (
            <div key={batch.batchId} className="mt-6">
              <p className="text-mini font-bold text-black">
                {batch.department} · {formatBankPayPeriod(batch.periodMonth)} · {batch.branchName}
              </p>
              <div className="mt-2 overflow-x-auto">
                <table className="w-full border-collapse text-2xs">
                  <thead>
                    <tr style={{ backgroundColor: 'rgb(245, 245, 245)' }}>
                      <th className="px-1.5 py-2 text-left font-bold" style={{ color: 'rgb(80, 80, 80)' }}>
                        Beneficiary
                      </th>
                      <th className="px-1.5 py-2 text-left font-bold" style={{ color: 'rgb(80, 80, 80)' }}>
                        Bank
                      </th>
                      <th className="px-1.5 py-2 text-left font-bold" style={{ color: 'rgb(80, 80, 80)' }}>
                        Bank code
                      </th>
                      <th className="px-1.5 py-2 text-left font-bold" style={{ color: 'rgb(80, 80, 80)' }}>
                        Account
                      </th>
                      <th className="px-1.5 py-2 text-right font-bold" style={{ color: 'rgb(80, 80, 80)' }}>
                        Amount
                      </th>
                      <th className="px-1.5 py-2 text-left font-bold" style={{ color: 'rgb(80, 80, 80)' }}>
                        Narration
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {batch.rows.map((row, idx) => (
                      <tr key={`${batch.batchId}-${idx}`}>
                        <td className="px-1.5 py-1.5 align-top">
                          {row.beneficiaryName || row.staffName || 'Unknown'}
                        </td>
                        <td className="px-1.5 py-1.5 align-top">{row.bankName || 'N/A'}</td>
                        <td className="px-1.5 py-1.5 align-top font-semibold tabular-nums">
                          {row.bankCode || 'N/A'}
                        </td>
                        <td className="px-1.5 py-1.5 align-top tabular-nums">
                          {row.accountNumber || 'N/A'}
                        </td>
                        <td className="px-1.5 py-1.5 text-right align-top tabular-nums">
                          {money(row.amount)}
                        </td>
                        <td className="px-1.5 py-1.5 align-top">{bankPayNarration(row)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="mt-2 text-2xs font-bold text-black">
                Batch total: {money(batchTotal)} · {batch.rows.length} line(s)
              </p>
            </div>
          );
        })}

        <div
          className="mt-10 flex justify-between text-[8px] leading-none"
          style={{ color: 'rgb(150, 150, 150)' }}
        >
          <span>Generated by Yannis</span>
          <span>Page 1</span>
        </div>
      </div>
    </div>
  );
}
