"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STOCK_STATE = exports.DEPLOYMENT_TYPE = exports.ADJUSTMENT_CATEGORY = exports.PAYOUT_STATUS = exports.INVOICE_STATUS = exports.FUNDING_STATUS = exports.TRANSFER_STATUS = exports.MOVEMENT_TYPE = exports.USER_ROLE = exports.ORDER_STATUS = void 0;
exports.ORDER_STATUS = {
    UNPROCESSED: 'UNPROCESSED',
    CS_ENGAGED: 'CS_ENGAGED',
    CONFIRMED: 'CONFIRMED',
    CANCELLED: 'CANCELLED',
    ALLOCATED: 'ALLOCATED',
    DISPATCHED: 'DISPATCHED',
    IN_TRANSIT: 'IN_TRANSIT',
    DELIVERED: 'DELIVERED',
    PARTIALLY_DELIVERED: 'PARTIALLY_DELIVERED',
    RETURNED: 'RETURNED',
    RESTOCKED: 'RESTOCKED',
    WRITTEN_OFF: 'WRITTEN_OFF',
    COMPLETED: 'COMPLETED',
};
exports.USER_ROLE = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    HEAD_OF_MARKETING: 'HEAD_OF_MARKETING',
    MEDIA_BUYER: 'MEDIA_BUYER',
    HEAD_OF_CS: 'HEAD_OF_CS',
    CS_AGENT: 'CS_AGENT',
    FINANCE_OFFICER: 'FINANCE_OFFICER',
    HEAD_OF_LOGISTICS: 'HEAD_OF_LOGISTICS',
    WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
    TPL_MANAGER: 'TPL_MANAGER',
    TPL_RIDER: 'TPL_RIDER',
    HR_MANAGER: 'HR_MANAGER',
};
exports.MOVEMENT_TYPE = {
    INTAKE: 'INTAKE',
    RESERVATION: 'RESERVATION',
    ALLOCATION: 'ALLOCATION',
    DISPATCH: 'DISPATCH',
    DELIVERY: 'DELIVERY',
    RETURN: 'RETURN',
    RESTOCK: 'RESTOCK',
    WRITE_OFF: 'WRITE_OFF',
    TRANSFER_OUT: 'TRANSFER_OUT',
    TRANSFER_IN: 'TRANSFER_IN',
    ADJUSTMENT: 'ADJUSTMENT',
};
exports.TRANSFER_STATUS = {
    PENDING: 'PENDING',
    IN_TRANSIT: 'IN_TRANSIT',
    RECEIVED: 'RECEIVED',
    DISPUTED: 'DISPUTED',
};
exports.FUNDING_STATUS = {
    SENT: 'SENT',
    COMPLETED: 'COMPLETED',
    DISPUTED: 'DISPUTED',
};
exports.INVOICE_STATUS = {
    DRAFT: 'DRAFT',
    SENT: 'SENT',
    PAID: 'PAID',
    OVERDUE: 'OVERDUE',
    CANCELLED: 'CANCELLED',
};
exports.PAYOUT_STATUS = {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    PAID: 'PAID',
    REJECTED: 'REJECTED',
};
exports.ADJUSTMENT_CATEGORY = {
    BONUS: 'BONUS',
    EXTRA_SHIFT: 'EXTRA_SHIFT',
    PERFORMANCE: 'PERFORMANCE',
    DEDUCTION: 'DEDUCTION',
    CLAWBACK: 'CLAWBACK',
    OTHER: 'OTHER',
};
exports.DEPLOYMENT_TYPE = {
    SNIPPET: 'SNIPPET',
    IFRAME: 'IFRAME',
    HOSTED: 'HOSTED',
};
exports.STOCK_STATE = {
    AVAILABLE: 'AVAILABLE',
    RESERVED: 'RESERVED',
    ALLOCATED_TO_3PL: 'ALLOCATED_TO_3PL',
    IN_TRANSIT: 'IN_TRANSIT',
    DELIVERED: 'DELIVERED',
    RETURNED: 'RETURNED',
    WRITTEN_OFF: 'WRITTEN_OFF',
};
//# sourceMappingURL=index.js.map